doc-warnings: true
test-warnings: true
strictness: veryhigh
max-line-length: 120
pylint:
  disable:
    - missing-docstring
    - super-on-old-class
uses:
  - django
requirements:
  - misago/project_template/requirements.txt
ignore-paths:
  - docs
  - frontend
python-targets:
    - 2
    - 3