language: python
python:
  - "2.7"
install:
  - python setup.py install
  - misago-start.py testproject
  - pip install coveralls
script:
  - coverage run --source=misago testproject/manage.py test
  - coveralls
