dist: xenial
language: python
jobs:
  include:
    - python:
        - 3.6
      addons:
        postgresql: 9.4
      install:
        - pip install -U pip setuptools
        - python setup.py install
        - pip install coveralls pytest-cov
      before_script:
        - psql -c "create database travis_ci_test;" -U postgres
      script:
        - pytest --cov=misago
      after_success:
        - coveralls
    - name: "lint"
      python: 3.6
      install:
        - pip install -U pip setuptools
        - python setup.py install
        - pip install black pylint pylint-django
      script:
        - black --check devproject misago
        - pylint misago/acl misago/admin misago/cache