addons:
  postgresql: "9.4"
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install coveralls
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
script:
  - coverage run --source=misago setup.py test
after_success:
  - coveralls
