addons:
  postgresql: "9.4"
language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install -r misago/project_template/requirements.txt
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
script:
  - coverage run --source=misago runtests.py
after_success:
  - coveralls
